### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by MahmoudAwwad94** [gurov/work-time#2]
Hey 
thanks for this library but i have this issues when i try to import the library i got this error 

ERROR in ./node_modules/work-time/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/mahmoud/Documents/medic-app/node_modules/work-time/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/mahmoud/Documents/medic-app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:752:23)
    at plugin.done.then (/Users/mahmoud/Documents/medic-app/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by gurov** [comment]
@MahmoudAwwad94 Hi! Could you tell me you Angular version?

**Comment by gurov** [comment]
@MahmoudAwwad94 The bug has been fixed. 
Current dependencies: angular 7+, bootstrap 4+
